# This is a basic workflow to help you get started with Actions

name: Sync Drive to Notion

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.21.1
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          
      - name: Install dependencies
        run: pnpm install

      - name: Run script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SECRET_CLIENT_KEY: ${{ secrets.SECRET_CLIENT_KEY }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node index.js
